admin_email                = "gssrishi@gmail.com"
dev_project                = "learning-dataeng-dev"
dev_tf_service_account_id  = "dev-tf-provisioner-sa"
dataproc_runtime_sa_id     = "dataproc-runtime-sa"
airflow_orchestrator_sa_id = "airflow-orchestrator-sa"